version: '3.6'

services:
    db:
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - '5432:5432'
        build:
            dockerfile: Dockerfile
            context: ./db
        volumes:
            - ./db/volume/init/:/docker-entrypoint-initdb.d/
            - ./db/volume/pgdata:/var/lib/postgresql/data
    jupyterlab:
        build:
            context: ./jupyter
            dockerfile: Dockerfile
        container_name: jupyterlab
        ports:
            - 8888:8888
            - 4040:4040
        volumes:
            -   type: bind
                source: ./build/workspace
                target: /opt/workspace
    spark-master:
        image: spark-master:3.2.0
        container_name: spark-master
        ports:
            - 8080:8080
            - 7077:7077
        volumes:
            -   type: bind
                source: ./build/workspace
                target: /opt/workspace
    spark-worker-1:
        image: spark-worker:3.2.0
        container_name: spark-worker-1
        environment:
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=1024m
        ports:
            - 8081:8081
        volumes:
            -   type: bind
                source: ./build/workspace
                target: /opt/workspace
        depends_on:
            - spark-master
    spark-worker-2:
        image: spark-worker:3.2.0
        container_name: spark-worker-2
        environment:
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=1024m
        ports:
            - 8082:8081
        volumes:
            -   type: bind
                source: ./build/workspace
                target: /opt/workspace
        depends_on:
            - spark-master
    spark-worker-3:
        image: spark-worker:3.2.0
        container_name: spark-worker-3
        environment:
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=1024m
        ports:
            - 8083:8081
        volumes:
            -   type: bind
                source: ./build/workspace
                target: /opt/workspace
        depends_on:
            - spark-master
    spark-worker-4:
        image: spark-worker:3.2.0
        container_name: spark-worker-4
        environment:
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=1024m
        ports:
            - 8084:8081
        volumes:
            -   type: bind
                source: ./build/workspace
                target: /opt/workspace
        depends_on:
            - spark-master
