version: '3.3'
services:
    db:
        image: postgres:14.5
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
    stream:
        build:
            context: ./
            dockerfile: ./stream/Dockerfile
        command: tail -f /dev/null