version: '3.3'
services:
    db:
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - '5432:5432'
        build:
            dockerfile: Dockerfile
            restart: always
            context: ./db
        volumes:
            - ./volume:/docker-entrypoint-initdb.d/
        
        
    stream:
        build:
            context: ./
            dockerfile: ./stream/Dockerfile
        command: tail -f /dev/null