version: '2'
services:
  db:
    container_name: psql
    build:
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD= mantequila
    ports:
      - '5432:5432'
  qgisdesktop:
    image: kartoza/qgis-desktop:3.0
    hostname: qgis-server
    #build:
      #dockerfile: Dockerfile-qg
    volumes:
      # Wherever you want to mount your data from
      - ./gis:/gis
      # Unix socket for X11
      - /tmp/.X11-unix:/tmp/.X11-unix
    links:
      - db:db
    environment: 
      - DISPLAY=unix$DISPLAY
    command: /usr/bin/qgis
